package hr.unizg.fer.zemris.ppj.maheri.semantics;

enum PPJCProduction {
	PRIMARNI_IZRAZ_1, PRIMARNI_IZRAZ_2, PRIMARNI_IZRAZ_3, PRIMARNI_IZRAZ_4, PRIMARNI_IZRAZ_5,

	POSTFIX_IZRAZ_1, POSTFIX_IZRAZ_2, POSTFIX_IZRAZ_3, POSTFIX_IZRAZ_4, POSTFIX_IZRAZ_5, POSTFIX_IZRAZ_6,

	LISTA_ARGUMENATA_1, LISTA_ARGUMENATA_2,

	UNARNI_IZRAZ_1, UNARNI_IZRAZ_2, UNARNI_IZRAZ_3, UNARNI_IZRAZ_4,

	UNARNI_OPERATOR_1, UNARNI_OPERATOR_2, UNARNI_OPERATOR_3, UNARNI_OPERATOR_4,

	CAST_IZRAZ_1, CAST_IZRAZ_2,

	IME_TIPA_1, IME_TIPA_2,

	SPECIFIKATOR_TIPA_1, SPECIFIKATOR_TIPA_2, SPECIFIKATOR_TIPA_3,

	MULTIPLIKATIVNI_IZRAZ_1, MULTIPLIKATIVNI_IZRAZ_2, MULTIPLIKATIVNI_IZRAZ_3, MULTIPLIKATIVNI_IZRAZ_4,

	ADITIVNI_IZRAZ_1, ADITIVNI_IZRAZ_2, ADITIVNI_IZRAZ_3,

	ODNOSNI_IZRAZ_1, ODNOSNI_IZRAZ_2, ODNOSNI_IZRAZ_3, ODNOSNI_IZRAZ_4, ODNOSNI_IZRAZ_5,

	JEDNAKOSNI_IZRAZ_1, JEDNAKOSNI_IZRAZ_2, JEDNAKOSNI_IZRAZ_3,

	BIN_I_IZRAZ_1, BIN_I_IZRAZ_2,

	BIN_XILI_IZRAZ_1, BIN_XILI_IZRAZ_2,

	BIN_ILI_IZRAZ_1, BIN_ILI_IZRAZ_2,

	LOG_I_IZRAZ_1, LOG_I_IZRAZ_2,

	LOG_ILI_IZRAZ_1, LOG_ILI_IZRAZ_2,

	IZRAZ_PRIDRUZIVANJA_1, IZRAZ_PRIDRUZIVANJA_2,

	IZRAZ_1, IZRAZ_2,

	SLOZENA_NAREDBA_1, SLOZENA_NAREDBA_2,

	LISTA_NAREDBI_1, LISTA_NAREDBI_2,

	NAREDBA_1, NAREDBA_2, NAREDBA_3, NAREDBA_4, NAREDBA_5,

	IZRAZ_NAREDBA_1, IZRAZ_NAREDBA_2,

	NAREDBA_GRANANJA_1, NAREDBA_GRANANJA_2,

	NAREDBA_PETLJE_1, NAREDBA_PETLJE_2, NAREDBA_PETLJE_3,

	NAREDBA_SKOKA_1, NAREDBA_SKOKA_2, NAREDBA_SKOKA_3, NAREDBA_SKOKA_4,

	PRIJEVODNA_JEDINICA_1, PRIJEVODNA_JEDINICA_2,

	VANJSKA_DEKLARACIJA_1, VANJSKA_DEKLARACIJA_2,

	DEFINICIJA_FUNKCIJE_1, DEFINICIJA_FUNKCIJE_2,

	LISTA_PARAMETARA_1, LISTA_PARAMETARA_2,

	DEKLARACIJA_PARAMETRA_1, DEKLARACIJA_PARAMETRA_2,

	LISTA_DEKLARACIJA_1, LISTA_DEKLARACIJA_2,

	DEKLARACIJA_1,

	LISTA_INIT_DEKLARATORA_1, LISTA_INIT_DEKLARATORA_2,

	INIT_DEKLARATOR_1, INIT_DEKLARATOR_2,

	IZRAVNI_DEKLARATOR_1, IZRAVNI_DEKLARATOR_2, IZRAVNI_DEKLARATOR_3, IZRAVNI_DEKLARATOR_4,

	INICIJALIZATOR_1, INICIJALIZATOR_2,

	LISTA_IZRAZA_PRIDRUZIVANJA_1, LISTA_IZRAZA_PRIDRUZIVANJA_2,

}